# Generated by Django 3.2.7 on 2021-09-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('primary_name', models.CharField(max_length=100)),
                ('olid', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
