# Generated by Django 3.2.7 on 2021-11-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='search_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
