# Generated by Django 5.1.4 on 2025-01-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_openlibrarycache'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_multivolume',
            field=models.BooleanField(default=False, help_text='Indicates if this Work is a multi-volume set'),
        ),
        migrations.AddField(
            model_name='work',
            name='volume_number',
            field=models.IntegerField(blank=True, help_text='Optional volume number within a multi-volume set', null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='volume_title',
            field=models.CharField(blank=True, help_text='Optional specific title for this volume', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.CharField(choices=[('NOVEL', 'Novel'), ('POEM', 'Poem'), ('JOURNALISM', 'Journalism'), ('SHORT_STORY', 'Short Story'), ('COLLECTION', 'Anthology/Collection')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['is_multivolume', 'volume_number'], name='book_work_is_mult_90dd6e_idx'),
        ),
    ]
