# Generated by Django 5.1.4 on 2025-01-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_work_is_multivolume_work_volume_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='editors',
            field=models.ManyToManyField(related_name='edited_works', to='book.author'),
        ),
    ]
