# Generated by Django 5.1.4 on 2025-01-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_work_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
