# Generated by Django 5.1.4 on 2025-01-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_author_birth_date_author_death_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='alternate_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='author',
            name='alternate_olids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
