# Generated by Django 5.1.4 on 2025-01-28 04:44

from django.db import migrations, models

def populate_ids(apps, schema_editor):
    Author = apps.get_model('book', 'Author')
    for i, author in enumerate(Author.objects.all(), start=1):
        author.id = i
        author.save()

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_author_alternate_names_author_alternate_olids'),
    ]

    operations = [
        # First add the id field as nullable
        migrations.AddField(
            model_name='author',
            name='id',
            field=models.BigAutoField(null=True),
        ),
        # Run our function to populate IDs
        migrations.RunPython(populate_ids),
        # Make id the primary key and non-nullable
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(primary_key=True),
        ),
        # Make olid unique but not primary key
        migrations.AlterField(
            model_name='author',
            name='olid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
